### ISSUE TITLE
Sätze geblockt

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#10]
**Beschreibe den Fehler**: Wenn man mit einem Kind, wir haben es für Natalia explizit getestet, mehrere Gespräche nacheinander führt, dann gibt das Kind bereits gesagte Sätze nicht aus. 

Eine klare, nachvollziehbare Beschreibung des Fehlers.

**Welches Setup?**
1. Welche Trainee-ID: '...' TestAndre1, TestAndre2, Marie
2. Welcher Messzeitpunkt: '...' T1, T2, T3
3. Welches virtuelle Kind: '...' Natalia
4. 3. Welches Ereignis: '...' A
5. VC1 oder VC2? VC2
6. Windows 11 ja
7. Frische Installation des OS oder seit längerem genutzter PC/Laptop? vom 10.10.2023

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?** Führe mehrere Gespräche mit demselben Kind nacheinander. Dann werden es die bereits gesagten Sätze in einem späteren Gespräch nicht mehr zur Verfügung stehen.

Schritte um den Fehler zu reproduzieren, zum Beispiel:
1. Gehe zu '...'
2. Klicke auf '....'
3. Scroll down bis '....'
4. Fehler erscheint

**Welches Verhalten der App wird e
[Test_Natalia at.xlsx](https://github.com/peterfromberger/vc2-app-issues/files/13031206/Test_Natalia.at.xlsx)
rwartet?** Mit jedem neuen Gespräch sollen wieder alle Sätze zur Verfügung stehen.

Eine klare und nachvollziehbare Beschreibung, welches Verhalten der App erwartet wird.

**Screenshots** Ich habe eine Exceldatei angehängt, in der drei Gespräche mit Natalia enthalten sind, jeweils mit unterschiedlicher Schirftfarbe markiert. In Spalte answer_content und answer_topic sieht man zB in Zeile 685 dass Natalia in einem Gespräch mit Satz 7 des kritischen Themas endet und in Zeile 688 in einem ganz neuen Gespräch mit Satz 8 des kritischen Themas einsteigt.

Bitte <b>immer</b> einen (oder mehrere) Screenshot(s) des Fehlers einfügen.

**Zusätzliche Hinweise**

Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.

**Comment by AnnaViContact** [comment]
Die Fehlermeldung bezieht sich nicht nur auf Natalia. Das ist auch bei allen anderen Kindern aufgefallen. Ich hänge das Logfile an, in dem alle bisher geführten Gespräche enthalten sind. Man sieht, dass zu einmal abgegrasten Themen keine Sätze mehr ausgegeben werden.
[Test_VR-Training.xlsx](https://github.com/peterfromberger/vc2-app-issues/files/13031421/Test_VR-Training.xlsx)

**Comment by peterfromberger** [comment]
Ok, da stimmt etwas nicht, wie CS momentan vor einem neuen Training geladen wird. Möglicherweise muss ich wieder zur ursprünglichen Variante zurück und CS vor jedem Training vollständig neu starten. Ein reset funktionierte damals schon nicht und jetzt offensichtlich immer noch nicht. Ich arbeite daran und hoffe in der kommenden Version eine Lösung zu haben.

@AnnaViContact Sind denn die Kategorisierungen in der Excledatei so gut, dass ich sie für die Modellierung der Textklassifikation verwenden kann? Die Kategorien request und comment machen ganz große Probleme, da dafür einfach viel zu wenig Daten vorhanden sind.

**Comment by AnnaViContact** [comment]
Wir haben weitere Kommentare kodiert. Du findest sie in der angehängten Datei. Das ist die Datei, die ich dir letztens schon geschickt habe, sie enthält nun aber mehr Kommentare. Wir kodieren weiter, so dass es noch mehr Kommentare werden können.

Für die Kategorie request konnte ich nur noch zwei drei weitere Fälle finden. Das ist eine sehr seltene Kategorie, da sie kodiert werden sollte, wenn die Trainees um Wiederholung der Antwort des Kindes gebeten haben. Wurde offenbar nicht so oft gemacht. Ich habe nach "wie bitte", "wiederholen" etc. gesucht und nur sehr wenig gefunden. Die sind nun aber in der rekodierten Spalte enthalten. Darüber hinaus stehen nur die ursprünglichen so kodierten Fälle zu Verfügung. 

Könnte man die Kategorie in Chatscript umsetzen? Fälle, in denen Wie bitte? oder Kannst dud as nochmal sagen/wiederholen? sollte man doch so erfassen können. Die Fälle, in denen ein Trainee das, was er verstanden hat wiederholt und ein großes Fragezeichen dran setzt, die kann man wahrscheinlich nicht erwischen. 

ps: Die Kodierungen aus der Exceldatei der Testungen sind unzuverlässig, weil die HiWis zu Testzwecken mitunter gezielt bestimmte Kategorien kodiert haben, ohne dass die notwenigerweise richtig waren. 
[Rekodierungen Stand 02.11.2023 mit Wertelabel und Transkripten.xlsx](https://github.com/peterfromberger/vc2-app-issues/files/13243755/Rekodierungen.Stand.02.11.2023.mit.Wertelabel.und.Transkripten.xlsx)

**Comment by AnnaViContact** [comment]
Ich habe gesehen, dass du diesen Issue mit fixed in 1.8.0 geschlossen hast. Können wir die Version schon installieren? Aktuell können wir das VR-Training nur sehr eingeschränkt testen, weil die Kinder keine Sätze mehr ausspucken. Ich könnte die aktuelle Verison zwar neu installieren, aber dann sagen die Kinder die meisten Sätze wieder nur einmal.

**Comment by peterfromberger** [comment]
> Ich habe gesehen, dass du diesen Issue mit fixed in 1.8.0 geschlossen hast. Können wir die Version schon installieren? Aktuell können wir das VR-Training nur sehr eingeschränkt testen, weil die Kinder keine Sätze mehr ausspucken. Ich könnte die aktuelle Verison zwar neu installieren, aber dann sagen die Kinder die meisten Sätze wieder nur einmal.

Sobald die neue Version unsere interne Testung hinter sich hat, stelle ich sie selbstverständlich umgehend zur Verfügung.

**Comment by peterfromberger** [comment]
> Wir haben weitere Kommentare kodiert. Du findest sie in der angehängten Datei. Das ist die Datei, die ich dir letztens schon geschickt habe, sie enthält nun aber mehr Kommentare. Wir kodieren weiter, so dass es noch mehr Kommentare werden können.

Danke. Wir haben jetzt leider allmählich ein Zeitfenster erreicht, wo neue Daten nur noch schwer genutzt werden können. Ich muss, wenn neue Daten zur Verfügung stehen, den kompletten Prozess der Auswahl des am besten passenden Models und dessen Optimierung neu machen, was relativ viel Zeit kostet. Daher schlage ich vor, dass wir nun mit dem arbeiten, was wir haben, ich also die nun zur Verfügung gestellten Dateien als Grundlage nehme.

**Comment by peterfromberger** [comment]
> Könnte man die Kategorie in Chatscript umsetzen? Fälle, in denen Wie bitte? oder Kannst dud as nochmal sagen/wiederholen? sollte man doch so erfassen können. Die Fälle, in denen ein Trainee das, was er verstanden hat wiederholt und ein großes Fragezeichen dran setzt, die kann man wahrscheinlich nicht erwischen

Wenn CS nochmals umgearbeitet wird und beispielsweise eine Kategorie selbst bestimmt, dann hätte dies schon einige Konsequenzen für die App und ich bitte doch sehr darum, hier jetzt nichts mehr zu ändern sondern dass wir versuchen, das jetzt so, wie es aktuell konzeptioniert ist beizubehalten. Ich habe jedenfalls nicht mehr genügend Zeit, solche tiefgreifenden Änderungen umzusetzen und zu testen.

**Comment by peterfromberger** [comment]
> Die Kodierungen aus der Exceldatei der Testungen sind unzuverlässig, weil die HiWis zu Testzwecken mitunter gezielt bestimmte Kategorien kodiert haben, ohne dass die notwenigerweise richtig waren.


OK.

**Comment by AnnaViContact** [comment]
> > Wir haben weitere Kommentare kodiert. Du findest sie in der angehängten Datei. Das ist die Datei, die ich dir letztens schon geschickt habe, sie enthält nun aber mehr Kommentare. Wir kodieren weiter, so dass es noch mehr Kommentare werden können.
> 
> Danke. Wir haben jetzt leider allmählich ein Zeitfenster erreicht, wo neue Daten nur noch schwer genutzt werden können. Ich muss, wenn neue Daten zur Verfügung stehen, den kompletten Prozess der Auswahl des am besten passenden Models und dessen Optimierung neu machen, was relativ viel Zeit kostet. Daher schlage ich vor, dass wir nun mit dem arbeiten, was wir haben, ich also die nun zur Verfügung gestellten Dateien als Grundlage nehme.

Ok

**Comment by peterfromberger** [comment]
fixed in v1.8.0
