### ISSUE TITLE
Im Chatfeld des Kindes in Operatorapp wird nichts angezeigt

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#11]
**Beschreibe den Fehler** In einigen Gesprächen mit Natalia fiel auf, dass zwar ein Audio von Natalia ausgegeben wird, das entsprechende Chatfeld aber leer bleibt. Im Logfile steht in der Spalte answer_content dann auch NaN. 

Ich hänge eine Datei an, in der das in Spalte answer_content nachvollzogen werden kann.

Eine klare, nachvollziehbare Beschreibung des Fehlers.

**Welches Setup?**
1. Welche Trainee-ID: '...' TestAndre1, TestAndre2, Marie
2. Welcher Messzeitpunkt: '...' t2, t3, t1
3. Welches virtuelle Kind: '...' Natalia
4. 3. Welches Ereignis: '...' A
5. VC1 oder VC2? VC2
6. Windows 11 ja
7. Frische Installation des OS oder seit längerem genutzter PC/Laptop? 10.10.2023

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?** kann nicht sicher gesagt werden

Schritte um den Fehler zu reproduzieren, zum Beispiel:
1. Gehe zu '...'
2. Klicke auf '....'
3. Scroll down bis '....'
4. Fehler erscheint

**Welches Verhalten der App wird erwartet?**

Eine klare und nachvollziehbare Beschreibung, welches Verhalten der App erwartet wird.

**Screenshots**

Bitte <b>immer</b> einen (oder mehrere) Screenshot(s) des Fehlers einfügen.

**Zusätzliche Hinweise**

Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.
[Test_Natalia at.xlsx](https://github.com/peterfromberger/vc2-app-issues/files/13031272/Test_Natalia.at.xlsx)

**Comment by peterfromberger** [comment]
fixed in 1.8.0
