### ISSUE TITLE
in VC2 funktioniert Tonaufnahme nicht

### ISSUE THREAD

**Issue by thilona** [peterfromberger/vc2-app-issues#12]
**Beschreibe den Fehler**

In VC2 funktioniert die Tonaufnahme über den Controller nicht. Trotz mehrmaligem Versuch bei zwei unterschiedlichen Trainees. Das Tutorial funktioniert und die Wörter werden erkannt und angezeigt. Nur im VR-Trainingsgespräch nicht. Hören ist möglich. In VC1 funktioniert sowohl das Tutorial als auch das Interview. Das Gesagte wird in VC1 erkannt und das Gespräch kann ablaufen. 

**Welches Setup?**
1. Welche Trainee-ID: 'VC2: nancy_kind1 und nancy_kind2'
2. Welcher Messzeitpunkt: 'Baseline 1 und 2, Training 1'
3. Welches virtuelle Kind: 'VC2: Luisa, Natalia, Andre; VC1: Luisa'
4. 3. Welches Ereignis: 'nach dem Tutorial kann das Gespräch nicht beginnen, da Gesagtes nicht erkannt wird und die Fehlermeldung "Tonaufnahme von App nicht erkannt" wird angezeigt'
5. VC1 oder VC2? nur VC2
6. Windows 11
7. Frische Installation des OS oder seit längerem genutzter PC/Laptop?

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?**

Schritte um den Fehler zu reproduzieren, zum Beispiel:
1. Gehe zu '...'
2. Klicke auf '....'
3. Scroll down bis '....'
4. Fehler erscheint

**Welches Verhalten der App wird erwartet?**

Gesprochenes wird erkannt.

**Screenshots**

Bitte <b>immer</b> einen (oder mehrere) Screenshot(s) des Fehlers einfügen.

**Zusätzliche Hinweise**

Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.

**Comment by peterfromberger** [comment]
@thilona Die Hinweise der Fehlermeldung hast du befolgt?

**Comment by peterfromberger** [comment]
@thilona Und das passiert auch nach einem vollständigen Neustart der App?

**Comment by peterfromberger** [comment]
AK ist noch nicht vollständig implementiert, daher auch kein Bug.
