### ISSUE TITLE
Workaround Feedback

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#13]
Du hast in der Übersicht angegeben, welche Kategorien schlecht erkannt werden können. Bei einigen ist das unproblematisch, weil sie so selten sind oder solche Fragekategorien fälschlicherweise gewählt werden, die aus derselben Klasse (erwünschte vs. unerwünschte Fragen) kommen. Auch das fällt für den Gesprächsverlauf nicht so ins Gewicht. Bei einigen wird sich die Fehlkategorisierung aber ungünstig auf das Feedback auswirken, weshalb wir eine Bitte/einen Vorschlag für einen Workaround haben:  

#Workaround Feedback: Im Prinzip geht es darum, dass der Operator in der Zeit, in der die Teilnehmenden die Fragen zum Gespräch beantworten, die Beispiele, die für das Feedback vorgesehen sind bzgl. ihrer Eignung einschätzt – und zwar bezogen auf a) die Verständlichkeit (so können wir Probleme bei der Spracherkennung umgehen) und bezogen b) auf die richtige Zuordnung der Kategorie. Beispiele, die als nicht geeignet eingeschätzt werden, werden abgewählt und stattdessen wird ein anderes Beispiel gewählt/zufällig gezogen. Kannst du sagen, ob das ein im Prinzip technisch umsetzbarer Workaround ist? Wenn es im Prinzip geht, es aber zu aufwändig ist, das für alle Kategorien umzusetzen, für die es Feedback gibt, könnte man es auch auf Kategorien begrenzen, die besonders kritisch sind (zB Suggestion).

**Comment by peterfromberger** [comment]
Technisch ist dies selbstverständlich möglich, zeitlich jedoch drei Wochen vor „Abgabe“ nicht. Ich bin verantwortlich, dass bis Ende des Jahres eine technisch funktionierende App vorliegt, die den Vorgaben des Antrages entspricht. Diese Verantwortung kann ich nicht übernehmen, wenn ich jetzt kurz vor Schluss noch so massive Änderungen durchführen würde. Das erfordert doch einen Umbau in fast allen Bereichen, so dass ich das einfach nicht mehr schaffe - bei gleichzeitiger suffizienter Testung der Änderungen. Im Antrag steht dazu auch nichts und auch nicht in den Änderungen, die sich aus AP 2 ergeben. Tut mir leid.
Der beste Workaround für (a) ist die Nutzung eines Headsets mit einem besseren Mikrofon oder ein anderes Mikrofon zu nutzen als das in die Vive integrierte (das ist wirklich ziemlich schlecht). Wir arbeiten hier bei uns mit neueren/anderen Headsets, da ist es schon besser. Zu VC 1-Zeiten war die HTC das beste Modell insgesamt, bei Antragstellung von VC 2 nicht mehr. Weshalb ihr dennoch die HTC Vive gekauft habt, weiß ich nicht. Aber auch ein externes, gutes Mikrofon ist grundsätzlich nutzbar; man kann das in SteamVR einstellen, welches Mikrofon genutzt werden soll. Zu (b): da habe ich keine Idee für einen pragmatischen workaround. Wenn es momentan so ist, dass das Feedback weniger Nutzbar ist als vorher in VC 1 (und da zeigt ja das paper, dass es funktioniert hat), dann muss man auf die automatische Kategorisierung verzichten und wieder von einem Menschen die Kategorisierung vornehmen lassen. 
Zudem finde ich es für das immersive Gespräch unglaublich angenehm, wenn das Kind wirklich direkt antwortet (die Reaktionszeiten des virtuellen Kindes sind jetzt schon ziemlich beeindruckend im Vergleich zu VC 1). Das klappt also mit der automatischen Klassifikation schon ziemlich gut und man hat mehr als mit menschlicher Kodierung das Gefühl eines realistischen Gespräches. Wenn wir jetzt wieder einen Versuchsleiter einbauen, würden wir diesen positiven Effekt verlieren. Daher: entweder (ganz) automatisch oder eben nicht automatisch.

**Comment by AnnaViContact** [comment]
Nur zum Verständnis: Ist es tatsächlich so, dass in allen Bereichen Umbauten vorgenommen werden müssten und nicht nur im Feedbackteil? Wir hatten uns das so vorgestellt, dass nach dem Ende des Gespräches, während die Vp Fragebögen ausfüllt, die ausgelosten Beispiele für das Feedback dem Operator angezeigt werden, der die bestätigen oder ablehnen kann, und dass bei Ablehnung ein neues Beispiel entsprechend der bestehenden Regeln gezogen wird.
Das Feedback ist neben dem Üben der zentrale Aspekt des Trainings. In VC1 war es so, dass die Teilnehmenden immer mal gerätselt haben, was das heißt, was da im Feedback steht. Wenn nun zusätzlich zur Spracherkennung eine weniger gute Kodierung kommt, kann das den Impact des Feedbacks evtl. nachhaltig mindern.

Genau, im Antrag steht zur Spracherkennung nichts, weil es hieß, bzgl. der Spracherkennung kann man nichts ändern. Im AP2-Papier haben wir das Thema Spracherkennung jedoch schon angesprochen und betont, dass die App von einer Verbesserung der Spracherkennung profitieren würde, weil ein substanzieller Anteil der Trials betroffen war. An einen Workaround war damals noch nicht zu denken, weshalb wir uns gefreut haben, als Hermann meinte, dass man durch das Einspielen der neuen Kaldi-Version etwas verbessern könne. 

Wir haben die Brille gekauft, weil wir verstanden haben, dass wir die Brille kaufen sollen, die in FL und GÖ auch verwendet wird. Wir beschaffen nun ein externes Mikro. Habt ihr auch Erfahrungen mit Mikros gemacht und könnt eins empfehlen?

**Comment by AnnaViContact** [comment]
[Beispiele Kodierung Suggestion Rapport überprüft.xlsx](https://github.com/peterfromberger/vc2-app-issues/files/13601932/Beispiele.Kodierung.Suggestion.Rapport.uberpruft.xlsx)
In Spalte x und y haben wir Suggestion und Rapportklassifikationen überprüft. Insbesondere bei Suggetsion zeigten sich auch hier viele falsch Positive.

**Comment by peterfromberger** [comment]
> Nur zum Verständnis: Ist es tatsächlich so, dass in allen Bereichen Umbauten vorgenommen werden müssten und nicht nur im Feedbackteil? Wir hatten uns das so vorgestellt, dass nach dem Ende des Gespräches, während die Vp Fragebögen ausfüllt, die ausgelosten Beispiele für das Feedback dem Operator angezeigt werden, der die bestätigen oder ablehnen kann, und dass bei Ablehnung ein neues Beispiel entsprechend der bestehenden Regeln gezogen wird.

Ja, das ist tatsächlich so. Beispielsweise sind die Fenster, die sich öffnen, nun durch die App angesteuert und nicht mehr (wie bei VC 1) einfach in einem Webbrowser. Alleine zwei parallele Fenster zu bauen, die gleichzeitig bedient und für den jeweiligen Nutzer im Fokus sind, ist schwierig. Denn es läuft alles auf einem PC. Ich müsste mir etwas überlegen, wie an einem PC zwei Personen gleichzeitig Eingaben machen können, ohne dass der andere Nutzer am gleichen PC aber mit anderem Fenster gestört wird. Also zwei Nutzer, zwei Mäuse und die zwei Eingaben dürfen sich nicht stören. Da gibt es nichts out-of-the-box und ich muss das ganz von Grunde auf selber machen. Das nur mal so als Beispiel, wie komplex die Umsetzung eurer Idee ist.

**Comment by peterfromberger** [comment]
> Das Feedback ist neben dem Üben der zentrale Aspekt des Trainings. In VC1 war es so, dass die Teilnehmenden immer mal gerätselt haben, was das heißt, was da im Feedback steht. Wenn nun zusätzlich zur Spracherkennung eine weniger gute Kodierung kommt, kann das den Impact des Feedbacks evtl. nachhaltig mindern.

Das ist mir schon bewusst. Ich habe immer darauf hingewiesen, dass es nicht sicher ist, dass die automatische Klassifizierung ausreichend gut funktioniert und man sich einen Plan B überlegen muss, wenn nicht. Ich habe da vor Wochen darauf hingewiesen und bekam als Rückmeldung nur, dass man da "vollstes Vertrauen" habe. Der Plan B kann aber nicht sein, innerhalb von nunmehr nur noch knapp zwei Wochen eine komplett neue Funktionalität einzubauen. Aufgrund meiner Erfahrungen bei der Programmierung von Anwendungen kann das einfach nicht mehr valide umgesetzt werden. Am aller einfachsten wäre es, die Frage-Antwort-Beispiele aus dem Feedback zu nehmen. Funktionen zu entfernen ist relativ easy. Wir wissen doch gar nicht, ob dieses Element des Feedbacks so wichtig ist, oder haben wir Daten dazu, welche Elemente des Feedbacks zu einem Erfolg führen (der ja entsprechend des Manuskriptes da ist)?

**Comment by peterfromberger** [comment]
> Genau, im Antrag steht zur Spracherkennung nichts, weil es hieß, bzgl. der Spracherkennung kann man nichts ändern. Im AP2-Papier haben wir das Thema Spracherkennung jedoch schon angesprochen und betont, dass die App von einer Verbesserung der Spracherkennung profitieren würde, weil ein substanzieller Anteil der Trials betroffen war. An einen Workaround war damals noch nicht zu denken, weshalb wir uns gefreut haben, als Hermann meinte, dass man durch das Einspielen der neuen Kaldi-Version etwas verbessern könne.

Ein neues Modell (es geht ja nicht nur um die Kaldi-Version, sondern welches Modell genutzt wird) alleine bedeutet nicht, dass es für unseren Anwendungsfall auch besser ist. Ich frage mich eher, weshalb euch Hermann nicht den Tipp mit dem Mikrofon gegeben hat und euch darauf hingewiesen hat, dass wir bereits mit anderen Headsets arbeiten. Die neuen Modelle für Kaldi sind statistisch nur um wenige Prozentpunkte besser als das Alte. Ich würde davon keine Verbesserung erwarten, die für das Feedback suffizient ist.

Zudem wird Kaldi in der Form von VC 1 gar nicht mehr genutzt (also nicht mehr im Sinne eines eigenen Servers). ich musste das ja alles in eine Anwendung integrieren, was ich für das Kaldi-Sprachmodell nun direkt in Unity über C# gemacht habe.

**Comment by peterfromberger** [comment]
> Habt ihr auch Erfahrungen mit Mikros gemacht und könnt eins empfehlen?

Leider nein.

**Comment by peterfromberger** [comment]
Idee nicht umsetzbar in der Kürze der Zeit.
