### ISSUE TITLE
Kommentare vs. Facilitator

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#14]
#Kommentare vs. Facilitator: Die beiden Kategorien werden häufig verwechselt. Das ist nachvollziehbar, weil alle Kommentare ursprünglich als Facilitator kodiert wurden, da es die Kategorie Kommentare noch nicht gab. Hier könnte eine erneute Modellierung mit weiteren überprüften Kodierungen eine Verbesserung bringen. Wenn du dazu noch Kapazität hast, würden wir dir den Datensatz schicken. Sonst leben wir mit der Unschärfe.

**Comment by peterfromberger** [comment]
Die Werte sind so schlecht, dass ihr schon sehr viele zuätzliche Kommentare haben müsstet. Zudem bedeutet ein neuer Datensatz, dass ich fast alle Modelle nochmals neu machen muss, also auch nochmals überprüfen muss ob dann nicht vielleicht andere Modelle mit anderen Parametern (die Modelle haben ja eine Vielzahl an parametern, die man berücksichtigen/ändern kann und man muss quasi immer alle Varianten durchspielen um sicherzugehen, dass man auch das beste Modell hat) besser sind. Das ist sehr zeitaufwändig. Aber schickt mir einmal die Daten und ich mache zumindest einen Testlauf....ich kann aber nicht versprechen, dass ich das noch umfänglich schaffe.

**Comment by AnnaViContact** [comment]
[Rekodierungen Stand 05.12.2023 mit Wertelabel.xlsx](https://github.com/peterfromberger/vc2-app-issues/files/13578828/Rekodierungen.Stand.05.12.2023.mit.Wertelabel.xlsx)

**Comment by AnnaViContact** [comment]
Wir haben alle Facilitator überprüft, so dass jetzt die maximal mögliche Differenzierbarkeit in den Daten enthalten sein sollte.

**Comment by peterfromberger** [comment]
in v2.0.0 dann neue Modelle auf Basis des neuen Datensatzes. Es gibt aber nur minimale Verbesserungen...
