### ISSUE TITLE
Rapport/Suggestion -> Suggestion/Rapport

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#15]
#Rapport/Suggestion: Bei der Kodierung durch Operator war die Rangfolge der beiden Kategorien genau anders herum, also erst Suggestion ja/nein, dann Rapport ja/nein. Eine suggestive Frage kann nicht mehr als Rapportäußerungen kodiert werden. Gibt es Gründe für den Wechsel der Rangfolge in der automatischen Kategorisierung?

**Comment by peterfromberger** [comment]
Meine Idee war, zuerst das Modell zu nehmen, dass eine höhere Genauigkeit hat. Denn Rapport und Suggestion schließen sich ja aus, oder? Und dann sind wenigstens die Ergebnisse für Rapport halbwegs brauchbar. ich hatte es ursprünglich tatsächlich andersherum, aber da hatte ich den Eindruck, dass viel zu häufig Suggestion fälschlicherweise True wurde und das hat dann jedes flüssige Gespräch verhindert.

Aber es ist eure Entscheidung und ich kann die Reihenfolge ohne großen Aufwand wieder umändern.

**Comment by AnnaViContact** [comment]
Manchmal ist es so, dass eine Äußerung rapporthaltig wirkt; weil sie aber auch suggestiv ist, kann sie jedoch nicht so kodiert werden. Das sind aber eine geringe Anzahl an Fällen, so dass wir zugunsten der höheren Genauigkeit gern bei dem aktuellen Modell bleiben wollen.

**Comment by peterfromberger** [comment]
[Beispiele Kodierung Suggestion Rapport überprüft.xlsx](https://github.com/peterfromberger/vc2-app-issues/files/13601932/Beispiele.Kodierung.Suggestion.Rapport.uberpruft.xlsx)
In Spalte x und y haben wir Suggestion und Rapportklassifikationen überprüft. Insbesondere bei Suggetsion zeigten sich auch hier viele falsch Positive.

**Comment by peterfromberger** [comment]
> Insbesondere bei Suggetsion zeigten sich auch hier viele falsch Positive.

Das überrascht mich angesichts der Ergebnisse nicht, die sagen ja schon das Gleiche. Es sind halt 15% FP aus den alten Daten dabei...oder verstehe ich etwas falsch?

**Comment by peterfromberger** [comment]
in v2.0.0 dann neue Modelle auf Basis des neuen Datensatzes. Es gibt aber nur minimale Verbesserungen...
