### ISSUE TITLE
Anfangsaufgabe: Kritisches Thema raus

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#16]
#kritisches Thema: Diese Variable tritt so selten auf, dass wir sie ganz aus dem Training nehmen können

**Comment by peterfromberger** [comment]
Ich möchte ungern zu diesem späten Zeitpunkt noch etwas an den Kategorien insgesamt ändern. Für die ML Modelle kann ich das machen, so dass einfach immer FALSE ausgegeben wird. Für die „klassische“ Variante mit Versuchsleiter nicht.

**Comment by AnnaViContact** [comment]
Finde ich nachvollziehbar.

**Comment by peterfromberger** [comment]
In v2.0.0 immer False für kritisches Ereignis
