### ISSUE TITLE
#VR-Brille: Man sieht die Texte im Tutorial und den Stichpunktzettel nur auf einer Seite der VR-Brille.FEHLER

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#17]
**Beschreibe den Fehler** #VR-Brille: Man sieht die Texte im Tutorial für die Spracherkennung und den Stichpunktzettel nur auf einer Seite der VR-Brille.

Eine klare, nachvollziehbare Beschreibung des Fehlers.

**Welches Setup?**
1. Welche Trainee-ID: '...'
2. Welcher Messzeitpunkt: '...'
3. Welches virtuelle Kind: alle
4. 3. Welches Ereignis: '...'
5. VC1 oder VC2?
6. Windows 11
7. Frische Installation des OS oder seit längerem genutzter PC/Laptop? ja

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?** passiert immer

Schritte um den Fehler zu reproduzieren, zum Beispiel:
1. Gehe zu '...'
2. Klicke auf '....'
3. Scroll down bis '....'
4. Fehler erscheint

**Welches Verhalten der App wird erwartet?**

Das Bild soll rechts und links zu sehen sein.

**Screenshots**

Bitte <b>immer</b> einen (oder mehrere) Screenshot(s) des Fehlers einfügen.

**Zusätzliche Hinweise**

Wenn es nichts App-Spezifisches ist, woran kann es liegen?

**Comment by peterfromberger** [comment]
fixed in v2.0.1
