### ISSUE TITLE
#Rangreihe Fragekategorien

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#18]
#Rangreihe Fragekategorien: Die Fragekategorien sind im Kreisdiagramm nicht entsprechend ihrem Grad an Unerwünschtheit aufgelistet. Vor allem die Kategorie „Kommentar“ fällt auf. 

**Welches Setup?**
1. Welche Trainee-ID: '...' jede
2. Welcher Messzeitpunkt: '...' Training
3. Welches virtuelle Kind: '...' alle
4. 3. Welches Ereignis: '...' alle
5. VC1 oder VC2? 
6. Windows 11
7. Frische Installation des OS oder seit längerem genutzter PC/Laptop? ja

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?**

passiert immer beim Feedback zur Fragekategorie

**Welches Verhalten der App wird erwartet?**

Wir bitten dich, die Kategorien in diese Reihenfolge zu bringen: EA, FA, BF, KM, AF, JN, UF, SF

![grafik](https://github.com/peterfromberger/vc2-app-issues/assets/147516764/d9cfffea-4245-42da-9407-ba0de90363fe)

**Screenshots**

Bitte <b>immer</b> einen (oder mehrere) Screenshot(s) des Fehlers einfügen.

**Zusätzliche Hinweise**

Die Rangfolge der Unerwünschtheit der Kategorien sind in der angehängten Datei von Niels vom 14.09. 2023 beschrieben worden. 
[Regeln Feedback Fragekategorien - Änderungen 14.09.23 Änderungen Kommentar Suggestion.docx](https://github.com/peterfromberger/vc2-app-issues/files/13662157/Regeln.Feedback.Fragekategorien.-.Anderungen.14.09.23.Anderungen.Kommentar.Suggestion.docx)

**Comment by peterfromberger** [comment]
fixed in v2.0.1
