### ISSUE TITLE
#Anzeige der kodierten Fragekategorie

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#19]
Es ist von Vorteil, wenn der Operator im Verlauf des Gesprächs sieht, wie das Klassifikationsmodell die Fragekategorie einordnet, um Probleme beim Feedback zu antizipieren. 
Wir bitten dich in die Sprechblasen des transkribierten Textes eine Information mit einzublenden, welche Fragekategorie der Äußerung zugeordnet wurde. 
![Fragekategorie anzeigen](https://github.com/peterfromberger/vc2-app-issues/assets/147516764/b7ecec7a-e094-4847-9027-ed7454a21662)

**Comment by peterfromberger** [comment]
das ist nicht mehr umsetzbar.
