### ISSUE TITLE
FEHLER

### ISSUE THREAD

**Issue by thilona** [peterfromberger/vc2-app-issues#2]
**Beschreibe den Fehler**
Das VR-Training läuft nicht weiter. 

**Welches Setup?**
1. Welche Trainee-ID: 'nancy_vc22'
2. Welcher Messzeitpunkt: 'Baseline T2'
3. Welches virtuelle Kind: 'Luisa'

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?**
Schritte um den Fehler zu reproduzieren:
1. Gehe zu 'ViContact VR-Training VC2, Fragbögen nach dem VR-Training'
2. Klicke auf 'Fragebogen ausgefüllt und weiter'
3. Scroll down bis ''
4. Fehler: Dokumentation wird nicht gestartet, sondern ein Info-Button und Button zum Abbruch des Trainings sind auf dem Bildschirm zu sehen. 

**Welches Verhalten der App wird erwartet?**
Nach dem Ausfüllen der Fragebögen soll das Dokumentationsmodul starten.

**Screenshots**
Bitte Screenshots des Fehlers einfügen.

**Zusätzliche Hinweise**
Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.

**Comment by peterfromberger** [comment]
fixed in 1.5.3
