### ISSUE TITLE
#Workaround Feedback Suggestion

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#20]
#Workaround Feedback Suggestion: Das individuelle Feedback rauszunehmen, nimmt einen wichtigen Aspekt raus. Es soll drinbleiben. Beim Feedback zu Suggestion sind die Falsch Positiven problematisch. Sie kommen aufgrund der hohen Priorisierung von Suggestionsfragen auch oft ins Feedback. Wir wollen das Feedback so gestalten, dass es auch bei unzureichender Verständlichkeit des individuellen Beispiels verständliche Beispiele für Suggestivfragen enthalten sind.

**Welches Verhalten der App wird erwartet?**

Deshalb bitten wir dich, den Feedbacktext für Feedback zu Suggestion wie folgt zu ändern:
Das ist eine Suggestivfrage. 
Solche Fragen enthalten spezifische Vorannahmen und/oder Informationen, die nicht vorher vom Kind geäußert worden sind, z.B.: „Hat er dich geschlagen?“ 
Auch Auswahl- bzw. Ja-Nein-Fragen, in denen Sie kommunizieren, welche Antwort Sie erwarten, sind suggestiv, z.B. durch Äußerungen wie „nicht?“, „oder?“, „stimmt’s?“.
Kinder widersprechen falschen Vorannahmen häufig nicht und folgen stattdessen dem (vermeintlichen) Wissen von Erwachsenen. Antworten auf Suggestivfragen sind deshalb keine verlässliche Informationsquelle.
Zu dieser Kategorie gehören auch Äußerungen, die keine bestimmten neuen Informationen enthalten, aber eine Erwartungshaltung kommunizieren und das Kind damit unter Druck setzen, etwas zu erzählen, das Sie als befragende Person zufrieden stellt.
•	Die Behauptung, Sie wüssten, was passiert ist, z.B.: „So ist das doch immer.“
•	Eine starke emotionale Bewertung eines Ereignisses Ihrerseits, z.B.: „Das ist ja schrecklich.“ 
•	Direktes Negatives Feedback zu einer Antwort, z.B.: „Aber irgendwas muss doch passiert sein.“
•	Aufforderung zur Spekulation, z.B.: Wie könnte es denn gewesen sein?
•	Indirektes negatives Feedback durch Wiederholung einer Frage, die das Kind bereits beantwortet hat.

Vermeiden Sie die Verwendung von Suggestivfragen unbedingt!

Kannst du den Text von als Suggestion eingeschätzten Fragen ersetzen in: „Die Audioaufnahme konnte nicht transkribiert werden.“? 

**Screenshots**

Bitte <b>immer</b> einen (oder mehrere) Screenshot(s) des Fehlers einfügen.

**Zusätzliche Hinweise**

Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.

**Comment by peterfromberger** [comment]
Das ist nicht mehr umsetzbar.
