### ISSUE TITLE
#Fragebögen

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#21]
Ein Teil der Fragebögen wird aktuell noch in der VR-TrainingsApp erfasst. Im Praxistest wollen wir teils andere Dinge erfassen. 
Um das zu vereinheitlichen und flexibel zu sein, bitten wir dich, alle Fragebögen rauszunehmen.

**Comment by peterfromberger** [comment]
Diese Erkenntnis kommt leider zu spät. Das ist in der Kürze der Zeit nicht mehr umsetzbar.
