### ISSUE TITLE
Dokumentationsmodul

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#22]
#Dokumentationsmodul Tippfehler: In der Instruktion gibt es einen Tippfehler (Reihenfolge). 
#Wo werden die Dokumentationsdaten gespeichert? 
#Dokumentationsmodul Formulierung Instruktionen: Tests mit Ungeübten haben noch gezeigt, dass die Formulierungen nicht verständlich genug sind.
![Instruktion richtige Dokumentation](https://github.com/peterfromberger/vc2-app-issues/assets/147516764/b05bbc03-f43f-48bf-8cc8-9ffcee7661c0) 
ändern in: 
Vergleichen Sie Ihre Dokumentation mit der Aufzeichnung: Markieren Sie in der Aufzeichnung alle von Ihnen richtig dokumentierten Äußerungen vom Kind und Ihnen zum interventionsbedürftigen Ereignis mit einem grünen Textmarker. 

![Instruktion falsche Dokumentation](https://github.com/peterfromberger/vc2-app-issues/assets/147516764/7757b4b6-6ac5-46ca-a676-1b63aff519a9)

 
ändern in: 
Vergleichen Sie Ihre Dokumentation mit der Aufzeichnung: Markieren Sie nun in Ihrer Dokumentation alle von Ihnen falsch dokumentierten Äußerungen vom Kind und Ihnen zum interventionsbedürftigen Ereignis mit dem roten Textmarker. 
 
#Dokumentationsmodul Markierung: Zum besseren Handling würde beitragen
-	Man kann Markierungen nicht einzeln löschen. Radierer wäre sinnvoll oder dass „Markierung entfernen“ nur die letzte Markierung löscht. 
-	Markierte Farbe zu dunkel, man kann die Schrift, wenn markiert nicht mehr lesen.
-	Buttons („Markierung speichern“, „Markierung entfernen“, „Weiter“) zu nah aneinander
-	jeweiliges Feld für Markierungen hervorheben, damit man weiß, wo man markieren soll.
-	Bei Feedback der dokumentierten Angaben vom Kind die Markierungen im Teil des Befragers ausblenden

**Comment by peterfromberger** [comment]
Das Dokumentationsmodul liegt seit Monaten vor. Das ist jetzt nicht mehr umsetzbar.
