### ISSUE TITLE
#Luisa Angaben zum Ereignis

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#23]
**Beschreibe den Fehler**

Bei den Personen, die als Beteiligte in Frage kommen stehen die Brüder noch als Clemens und Johannes drin. 

**Welches Setup?**
1. Welche Trainee-ID: '...'
2. Welcher Messzeitpunkt: '...' alle
3. Welches virtuelle Kind: '...' Luisa
4. 3. Welches Ereignis: '...' alle
5. VC1 oder VC2?
6. Windows 11
7. Frische Installation des OS oder seit längerem genutzter PC/Laptop?

Gespräch mit Luisa führen und Angaben zum erfassten Ereignis machen

Schritte um den Fehler zu reproduzieren, zum Beispiel:
1. Gehe zu '...'
2. Klicke auf '....'
3. Scroll down bis '....'
4. Fehler erscheint

**Welches Verhalten der App wird erwartet?**

 Clemens und Johannes bitte ändern in Steve und Dominik.

**Screenshots**
![Screenshot Luisa](https://github.com/peterfromberger/vc2-app-issues/assets/147516764/1bfb0f3c-9db0-47aa-9a54-2bf6b63a7c69)

Bitte <b>immer</b> einen (oder mehrere) Screenshot(s) des Fehlers einfügen.

**Zusätzliche Hinweise**

Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.

**Comment by peterfromberger** [comment]
geändert in v2.0.1
