### ISSUE TITLE
Wechsel von Version 1 zu Version 2

### ISSUE THREAD

**Issue by thilona** [peterfromberger/vc2-app-issues#3]
**Beschreibe den Fehler**
Nach Beendigung der 8 Messzeitpunkte in der Version 1 kann nicht in die Version 2 gewechselt werden. Die Initiierung beginnt, bleibt aber stecken.

**Welches Setup?**
1. Welche Trainee-ID: '...'
2. Welcher Messzeitpunkt: '...'
3. Welches virtuelle Kind: '...'

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?**
Schritte um den Fehler zu reproduzieren:
1. Gehe zu 'VC1 und versuche nach einem Durchlauf eines Messzeitpunktes in die Version 2 zu wechseln'
2. Klicke auf 'Version 2'
3. Scroll down bis '....'
4. Version 2 lässt sich nicht öffnen, sondern bleibt in der Phase der Initiierung hängen. 

**Welches Verhalten der App wird erwartet?**
Ein Wechsel von VC1 in die Version 2.

**Screenshots**
Bitte Screenshots des Fehlers einfügen.

**Zusätzliche Hinweise**
Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.

**Comment by peterfromberger** [comment]
@thilona Kannst du mir sagen, was zuletzt bei der Initialisierung unter den Punkten stand, als es sich aufgehängt hat?

**Comment by thilona** [comment]
Lieber Peter,


ich denke es war irgendetwas mit "Reset...".


LG, Nancy

________________________________
Von: Peter Fromberger ***@***.***>
Gesendet: Donnerstag, 7. September 2023 10:51:44
An: peterfromberger/vc2-app-issues
Cc: Thilo, Nancy; Mention
Betreff: [+externe Mail+] Re: [peterfromberger/vc2-app-issues] Wechsel von Version 1 zu Version 2 (Issue #3)


@thilona<https://github.com/thilona> Kannst du mir sagen, was zuletzt bei der Initialisierung unter den Punkten stand, als es sich aufgehängt hat?

**Comment by peterfromberger** [comment]
fixed in version 1.5.4
