### ISSUE TITLE
Dokumentation geht nicht weiter, wenn Trainee in einem Gespräch kein kritisches Topic erreicht

### ISSUE THREAD

**Issue by thilona** [peterfromberger/vc2-app-issues#4]
![Screenshot 2023-09-07 100553](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/46813f3a-128d-47c8-8078-c99764a97d43)

**Beschreibe den Fehler**
In der Version 2 werden bei der Dokumentation die Aufzeichnungen des Gespräches nicht angezeigt und es können keine Markierungen vorgenommen werden.

**Welches Setup?**
1. Welche Trainee-ID: 'nancy_vc2'
2. Welcher Messzeitpunkt: 'Baseline T1'
3. Welches virtuelle Kind: 'Sara'

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?**
Schritte um den Fehler zu reproduzieren:
1. Gehe zu 'Dokumentation nach dem VR-Gespräch'
2. Klicke auf 'Dokumentation, Trainee Window'
3. Scroll down bis '....'
4. siehe Screenshot

**Welches Verhalten der App wird erwartet?**
Die Aufzeichnung des konkreten Gesprächsverlaufs der Angaben zum Missbrauch.

**Screenshots**
Bitte Screenshots des Fehlers einfügen.

**Zusätzliche Hinweise**
Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.

**Comment by peterfromberger** [comment]
das ist ein bekannter Fehler und ich habe bereits in Berlin (Mail vom 01.09.2023 an Anna) nachgefragt, wie wir damit umgehen sollen, wenn kein kritisches Topic in einem Gespräch erreicht wird.

**Comment by peterfromberger** [comment]
Rückmeldung am 11.09.: wenn kein kritTopic, dann die folgenden Schritte überspringen

**Comment by peterfromberger** [comment]
fixed in 1.5.5; funktioniert allerdings erst, wenn crit_event_progress dynamisch und nicht mehr statisch ist

**Comment by peterfromberger** [comment]
fixed in current version
