### ISSUE TITLE
mehrmalige Wiederholung im Training

### ISSUE THREAD

**Issue by thilona** [peterfromberger/vc2-app-issues#5]
**Beschreibe den Fehler**
Im VR-Gespräch kommt es zur mehrmaligen Wiederholung des gleichen Satzes wie "Einmal musste Mama auch ins Krankenhaus deswegen" und eine andere Antwort kommt erst nach fünf oder sechs maligen neuen Fragen. Dies passierte bei der Erzählaufforderung und Bestimmungsfragen. 

**Welches Setup?**
1. Welche Trainee-ID: 'nancy_vc2'
2. Welcher Messzeitpunkt: 'Training T1'
3. Welches virtuelle Kind: 'Natalia'

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?**
Schritte um den Fehler zu reproduzieren:
1. Gehe zu 'VR-Trainingsgespräch und stelle eine Frage an das Kind'
2. Klicke auf ''Erzählaufforderung''
3. Scroll down bis '....'
4. siehe Screenshot, Frage wird auch nicht in der Auflistung angezeigt, sondern Datum und Uhrzeit
![Screenshot 2023-09-07 103615](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/188bd88c-c5fa-442b-acd9-ed63e9bd4105)

**Welches Verhalten der App wird erwartet?**
Keine mehrmalige Wiederholung der Antwort bei anderer Fragestellung.

**Screenshots**
Bitte Screenshots des Fehlers einfügen.

**Zusätzliche Hinweise**
Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.

**Comment by peterfromberger** [comment]
@thilona Das ist ein CS Problem und wohl eher etwas, das man gerne geändert hätte, aber kein klassischer Bug im technischen Sinne

**Comment by nielskrause** [comment]
@peterfromberger @thilona  ist zu diesem Problem ein Logfile vorhanden? Es ist mir bisher bei Testen von CS allein noch nicht begegnet, ich schaue es mir aber gern mal an.

**Comment by peterfromberger** [comment]
Das ist der gleiche Fehler wie in Issue #11

Man kann das bei Natalia beobachten, dort wird mehrmals ein Satz hintereinander ausgegeben und dann die Folgesätze mit NaN im datensatz gekennzeichnet. NaN kommt aus der App und wird immer dann vergeben, wenn answer_content = "", also keinen Inhalt hat. Dann erscheint, wie im Screenshot zu sehen, keine Antwort des Kindes im Gesprächsverlauf.

Ich gehe momentan davon aus, dass es irgendwie ein Folgefehler von Issue #10 ist: hier habe ich den Fehler gefunden. Hat eigentlich nichts mit CS zu tun, sondern es wurde nicht der richtige Nutzer übernommen wodurch CS immer mit dem gleichen User gearbeitet hat, mit der Konsequenz, dass dann eben immer dort weitergemacht wurde, wo der letzte Trainee/Nutzer aufgehört hat. 

@nielskrause Kann es sein, dass CS irgendwann einfach nichts mehr ausgibt oder Sätze wiederholt, wenn man alle Antworten/Topics abgegrast hat? Warum dann aber immer noch ein sound-file ausgegeben wird, aber kein Antwort-Inhalt weiß ich nicht.

**Comment by peterfromberger** [comment]
Duplicate of #11

**Comment by peterfromberger** [comment]
@nielskrause Wenn du automatisch neue Nachrichten zu einem Issue bekommen möchtest, dann musst du dich immer als Assignee hinzufügen

![grafik](https://github.com/peterfromberger/vc2-app-issues/assets/6342336/0ea63796-4489-4674-9e4e-7e5a397cfd80)

**Comment by peterfromberger** [comment]
> Das ist der gleiche Fehler wie in Issue #11
> 
> Man kann das bei Natalia beobachten, dort wird mehrmals ein Satz hintereinander ausgegeben und dann die Folgesätze mit NaN im datensatz gekennzeichnet. NaN kommt aus der App und wird immer dann vergeben, wenn answer_content = "", also keinen Inhalt hat. Dann erscheint, wie im Screenshot zu sehen, keine Antwort des Kindes im Gesprächsverlauf.
> 
> Ich gehe momentan davon aus, dass es irgendwie ein Folgefehler von Issue #10 ist: hier habe ich den Fehler gefunden. Hat eigentlich nichts mit CS zu tun, sondern es wurde nicht der richtige Nutzer übernommen wodurch CS immer mit dem gleichen User gearbeitet hat, mit der Konsequenz, dass dann eben immer dort weitergemacht wurde, wo der letzte Trainee/Nutzer aufgehört hat.
> 
> @nielskrause Kann es sein, dass CS irgendwann einfach nichts mehr ausgibt oder Sätze wiederholt, wenn man alle Antworten/Topics abgegrast hat? Warum dann aber immer noch ein sound-file ausgegeben wird, aber kein Antwort-Inhalt weiß ich nicht.

ich meinte, man kann das in der in Issue #10 angehängten Excel-Datei bei Natalia (die letzten drei Trainingseinheiten in der Tabelle) mehrmals beobachten.

**Comment by nielskrause** [comment]
> > Das ist der gleiche Fehler wie in Issue #11
> > Man kann das bei Natalia beobachten, dort wird mehrmals ein Satz hintereinander ausgegeben und dann die Folgesätze mit NaN im datensatz gekennzeichnet. NaN kommt aus der App und wird immer dann vergeben, wenn answer_content = "", also keinen Inhalt hat. Dann erscheint, wie im Screenshot zu sehen, keine Antwort des Kindes im Gesprächsverlauf.
> > Ich gehe momentan davon aus, dass es irgendwie ein Folgefehler von Issue #10 ist: hier habe ich den Fehler gefunden. Hat eigentlich nichts mit CS zu tun, sondern es wurde nicht der richtige Nutzer übernommen wodurch CS immer mit dem gleichen User gearbeitet hat, mit der Konsequenz, dass dann eben immer dort weitergemacht wurde, wo der letzte Trainee/Nutzer aufgehört hat.
> > @nielskrause Kann es sein, dass CS irgendwann einfach nichts mehr ausgibt oder Sätze wiederholt, wenn man alle Antworten/Topics abgegrast hat? Warum dann aber immer noch ein sound-file ausgegeben wird, aber kein Antwort-Inhalt weiß ich nicht.
> 
> ich meinte, man kann das in der in Issue #10 angehängten Excel-Datei bei Natalia (die letzten drei Trainingseinheiten in der Tabelle) mehrmals beobachten.

Ja, ich sehe dieses Problem in dem Logfile. 

Bisher habe ich im reinen CS-Testen diesen Zustand noch nicht erreicht, werde es aber jetzt mal versuchen.

**Comment by nielskrause** [comment]
Ich habe das erste Gespräch mit Natalia im o.g. Logfile versucht nachzustellen, von Trial 1 / id 618 bis Trial 14 / id 631. 
CS-Log (Branch niels, Stand 15.09. - ich habe angenommen, dass dieser Stand aktuell in der App läuft): 
[log-nls1026.txt](https://github.com/peterfromberger/vc2-app-issues/files/13176922/log-nls1026.txt)


Folgendes fiel mir auf: 
In Annas Logfile erscheint `answer_content==NaN`, wenn ein Topic erschöpft ist (alle Antwortsätze ausgegeben) und weiter danach gefragt wird. 

- `answerCategory` ist in diesen Fällen im Log weiterhin `narrative` oder `specific`, 
- zu erwarten wäre aber `emptyTopic`. 

In meinem Versuch (s.u.) hat sich CS verhalten wie erwartet. 

Ich versuche weiter zu verstehen, warum emptyTopic nicht anspricht.

[[ Weitere (edit: nicht unbedingt mit diesem Problem verknüpfte)  unerwartete Werte in Annas Logfile: 

-  `chatPhase== start`, obwohl in SI-Gesprächen normalerweise `chatPhase==main` von Beginn an (in introduction.top festgelegt). 
- `emoType==NaN`, was eine Folge aus chatPhase sein dürfte, da `^emoHandler()` für SI-Bots in chatPhase==start keine Emotion vorsieht.
- `eventProgress == -999`


Das spricht dafür, dass das Gambit des Introduction-Topic (z. 3-5) am Anfang des Gesprächs nicht ordnungsgemäß durchlaufen wird. Dieses Gambit ist (bewusst) single-use, denn es soll, neben der ersten Aussage des vKindes, eine Reihe von Variablen auf den Startwert setzen. Ich kann mir das weiterhin nur über die User-Problematik aus #10 erklären. ]]

**Comment by peterfromberger** [comment]
Genau, die App nutzt die CS Version vom 15.09., wobei ich aufgrund der gt-Probleme die files aus dem nils-Branch gezogen habe.

> [[ Weitere (edit: nicht unbedingt mit diesem Problem verknüpfte) unerwartete Werte in Annas Logfile:
> 
>     * `chatPhase== start`, obwohl in SI-Gesprächen normalerweise `chatPhase==main` von Beginn an (in introduction.top festgelegt).
> 
>     * `emoType==NaN`, was eine Folge aus chatPhase sein dürfte, da `^emoHandler()` für SI-Bots in chatPhase==start keine Emotion vorsieht.
> 
>     * `eventProgress == -999`

In der App werden für die Speicherung der Daten in der Datenbank (und daher kommt ja Annas file) Fehlwerte entsprechend zu NaN (wenn string variable) oder -999 (wenn integer/float) umgewandelt, da die Datentabelle keine null-values oder None-values zulässt. Bei emoType wird ein empty string mit "NaN" ersetzt. Bei chatPhase wird ein empty string mit "start" ersetzt, allerdings unabhängig ob si oder li.

eventProgress: Das ist ein kleinerer Bug der schon behoben ist; bei eventProgress == 0 wurde ein -999 eingesetzt.

**Comment by nielskrause** [comment]
> Kann es sein, dass CS irgendwann einfach nichts mehr ausgibt oder Sätze wiederholt, wenn man alle Antworten/Topics abgegrast hat? Warum dann aber immer noch ein sound-file ausgegeben wird, aber kein Antwort-Inhalt weiß ich nicht.

[log-nls1026srv7.txt](https://github.com/peterfromberger/vc2-app-issues/files/13181878/log-nls1026srv7.txt)


Ich kann dieses Verhalten bei CS - unabhängig vom Stand eines Topics - dann (und bisher nur dann) reproduzieren, wenn ich zwar eine sinnvolle Fragekategorie eingebe, aber keine Frage an sich. Beispiel: `[invitation_to_tell] ` . Außerdem muss per Zusfallszahl answerCategory==narrative bestimmt sein.
Dann wird schriftlich keine Antwort ausgegeben und die Variable soundFile im Output hat denselben Wert wie zuvor. answerCategory verhält sich wie in Annas Logfile (ich bleibe mal bei dem Begriff, weil er eindeutig ist). Beispiele im angehängten Logfile in Zeile 16, 19 und 25.

Wenn die Zufallszahl > 80 ist, wird einfach eine generische Antwort gewählt, wie sonst auch (Bsp in Z. 18)

Ein bewusst gesetzter Typo im oob-Bereich wie bspw. [invitation_to_tel], vgl. Z. 26, führt zu einer Antwort aus dem Topic ignorance. 

Ich frage mich, welchen Input CS bei den fraglichen Trials von der App bekommen hat. Dafür brauche ich die CS-eigenen logfiles. Sobald ich Zugang zum Laborrechner habe, schaue ich danach. 

> eventProgress: Das ist ein kleinerer Bug der schon behoben ist; bei eventProgress == 0 wurde ein -999 eingesetzt.

Perfekt.

> In der App werden für die Speicherung der Daten in der Datenbank (und daher kommt ja Annas file) Fehlwerte entsprechend zu NaN (wenn string variable) oder -999 (wenn integer/float) umgewandelt, da die Datentabelle keine null-values oder None-values zulässt. Bei emoType wird ein empty string mit "NaN" ersetzt. Bei chatPhase wird ein empty string mit "start" ersetzt, allerdings unabhängig ob si oder li.

Das heißt, CS sendet leere Werte der betreffenden Variablen an die App. Das konnte ich bisher noch nicht reproduzieren.

**Comment by peterfromberger** [comment]
fixed in 1.8.0
