### ISSUE TITLE
In Dokumentation wird manchmal nicht richtig erkannt, dass über kinderschutzrelevantes Thema gesprochen wurde und dies auch dokumentiert wurde

### ISSUE THREAD

**Issue by thilona** [peterfromberger/vc2-app-issues#6]
**Beschreibe den Fehler**
In der Zusammenfassung der Dokumentation heißt es, dass der sexuelle Missbrauch nicht angesprochen wurde, obwohl das Häkchen dafür gesetzt ist. Dieses steht auch darunter in grüner Schrift. 

**Welches Setup?**
1. Welche Trainee-ID: 'nancy_vc2'
2. Welcher Messzeitpunkt: 'Training T2'
3. Welches virtuelle Kind: 'Laura'

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?**
Schritte um den Fehler zu reproduzieren:
1. Gehe zu 'Dokumentation'
2. Klicke auf 'Auswertung'
3. Scroll down bis '....'
4. Bei der Ausgabe der Zusammenfassung in der Dokumentation.

**Welches Verhalten der App wird erwartet?**
Die Zusammenfassung zum Ereignis in fettgedruckter Schrift sollte mit den angeklickten Häkchen übereinstimmen
![Screenshot 2023-09-07 110304](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/4d63146b-2620-4116-b0e9-fd56eda3bae5)
.

**Screenshots**
Bitte Screenshots des Fehlers einfügen.

**Zusätzliche Hinweise**
Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.

**Comment by peterfromberger** [comment]
fixed in 1.5.4
