### ISSUE TITLE
Gesprochenes wird nicht erkannt

### ISSUE THREAD

**Issue by thilona** [peterfromberger/vc2-app-issues#7]
**Das VR-Headset funktioniert, aber wenn ich spreche, passiert nichts, trotz mehrmaligem Versuch im VC1 und VC2. Wenn ich etwas sage, wartet das Programm und zählt die Zeit runter und meine Worte werden nicht gehört**

Eine klare, nachvollziehbare Beschreibung des Fehlers.

**Welches Setup?**
1. Welche Trainee-ID: 'nancy_vr11 und nancy_vr22'
2. Welcher Messzeitpunkt: 'VC1 Baseline 1 und 2; VC2 Baseline 1'
3. Welches virtuelle Kind: 'VC1: Sara und Constantin; VC2: Andre'
4. 3. Welches Ereignis: 'Im Tutorial wird der von mir gesprochene Satz "Das Wetter ist heute schön" nicht aufgenommen; auch beim Überspringen des Tutorials und im VR-Training reagiert das Kind nicht auf meine Frage, da diese nicht erkannt wird'
5. VC1 oder VC2? in beiden Versionen
6. Windows 11
7. Frische Installation des OS oder seit längerem genutzter PC/Laptop?

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?**

Schritte um den Fehler zu reproduzieren, zum Beispiel:
1. Gehe zu 'VC1, starte Tutorial'
2. Klicke auf 'Tutorial starten'
3. Scroll down bis '....'
4. Beim Drücken der unteren Taste am Handcontroller, der einsatzbereit ist (grünes Licht)
![Screenshot 2023-09-26 072213](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/3e5ff28d-7675-4c85-925b-d23455e50301)
![Screenshot 2023-09-26 073150](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/43ff1394-950d-4e01-b244-93b92f226ab7)
, und gleichzeitigem Sprechen wird das Gesprochene nicht erkannt.  

**Welches Verhalten der App wird erwartet?**

Der Satz wird erkannt und das Tutorial kann beendet werden bzw. das Kind reagiert auf das Gesprochene und das Programm nimmt den Satz auf.

**Screenshots**

Bitte <b>immer</b> einen (oder mehrere) Screenshot(s) des Fehlers einfügen.

**Zusätzliche Hinweise**

Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.

**Comment by peterfromberger** [comment]
Durchführungsfehler. In 1.6.1 ist Hinweis integriert, wenn system keine Aufnahme machen konnte.
