### ISSUE TITLE
Fehlermeldung bei den Fragen zum Ereignis nach dem VR-Training

### ISSUE THREAD

**Issue by thilona** [peterfromberger/vc2-app-issues#8]
**Das VR-Training ist beendet und nach dem Ausfüllen der Fragebögen kommen die beiden Fragen "Welches Ereignis wurde angesprochen?" und "Wer war daran beteiligt?" mit mehreren Antwortoptionen zum Ankreuzen. Nach dem Ankreuzen kommen Fehlermeldungen (siehe Screenshots)**

Eine klare, nachvollziehbare Beschreibung des Fehlers.

**Welches Setup?**
1. Welche Trainee-ID: 'nancy_vr2_training'
2. Welcher Messzeitpunkt: 'Baseline T1, Training T3 und Postmeasurement T1 '
3. Welches virtuelle Kind: 'Sara, Jason und Andre'
4. 3. Welches Ereignis: 'sex. Missbrauch und anderes interventionsbedürftiges Ereignis'
5. VC1 oder VC2? VC2
6. Windows 11
7. Frische Installation des OS oder seit längerem genutzter PC/Laptop?

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?**

Schritte um den Fehler zu reproduzieren, zum Beispiel:
1. Gehe zu 'Baseline T1'
2. Klicke auf 'Fragebögen. Beantworte die beiden Fragen zum Ereignis und kreuze die Beteiligten an'
3. Scroll down bis '....'
4. Fehler erscheint siehe Screenshots

**Welches Verhalten der App wird erwartet?**

Eine klare und nachvollziehbare Beschreibung, welches Verhalten der App erwartet wird.
![Screenshot 2023-09-26 133857](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/e3845ffc-f728-4f0a-85e0-767128a9fb68)
![Screenshot 2023-09-26 133926](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/2e274647-5975-45ff-8cb1-687b32fd0d9a)
![Screenshot 2023-09-26 133956](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/6d31881f-cfb3-4406-ae46-4c585acaea2c)
![Screenshot 2023-09-26 135420](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/cb75d7cf-964c-4152-9647-4448a8e24b4a)
![Screenshot 2023-09-26 135439](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/94825633-50a3-48ed-9469-f7b72381a698)
![Screenshot 2023-09-26 143005](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/43c78b91-925e-41a1-b66b-f249de6923cf)
![Screenshot 2023-09-26 143140](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/a8438634-39b4-4125-856a-1fb180d04496)
![Screenshot 2023-09-26 145558](https://github.com/peterfromberger/vc2-app-issues/assets/144107725/033c2730-d579-4056-8567-2c035808c8ac)

**Screenshots**

Bitte <b>immer</b> einen (oder mehrere) Screenshot(s) des Fehlers einfügen.

**Zusätzliche Hinweise**

Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.

**Comment by peterfromberger** [comment]
fixed in version 1.6.1
