### ISSUE TITLE
Einige Audios für narrative Antworten wurden nicht ausgegeben

### ISSUE THREAD

**Issue by AnnaViContact** [peterfromberger/vc2-app-issues#9]
**Beschreibe den Fehler**

Eine klare, nachvollziehbare Beschreibung des Fehler: Einige Audios für narrative Antworten wurden nicht ausgegeben (zB zwei wurden ausgegeben, zwei nicht, da eine wieder, dann wieder zwei nicht). Es war nicht erkennbar, nach welchem Prinzip sie nicht ausgegeben wurden. Eindruck war bei Erzählaufforderungen. Bei Prüfung hat er aber auch auf Bestimmungsfrage eine narrative Antwort nicht ausgegeben. 

**Welches Setup?**
1. Welche Trainee-ID: Marie, Justine
2. Welcher Messzeitpunkt: Baseline T1
3. Welches virtuelle Kind: Constantin
4. 3. Welches Ereignis: C, B
5. VC1 oder VC2? VC2
6. Windows 11: ja
7. Frische Installation des OS oder seit längerem genutzter PC/Laptop? PC nicht neu (neuer Labor-PC), aber auch noch nicht wirklich benutzt. Updates etc,. neu eingespielt.

**Welche Schritte sind notwendig, um den Fehler zu reproduzieren?**

Schritte um den Fehler zu reproduzieren, zum Beispiel: nicht sicher reproduzierbar
1. Gehe zu: Gespräch mit Constatin, Baseline T1
2. Klicke auf '....' Stelle Erzählaufforderung, ab und zu wird Audio nicht ausgegeben.
3. Scroll down bis '....'
4. Fehler erscheint

**Welches Verhalten der App wird erwartet?**

Eine klare und nachvollziehbare Beschreibung, welches Verhalten der App erwartet wird.: Dass Audio immer ausgegeben wird.

**Screenshots** Bei Audio nicht möglich. Zum Beispiel folgende Sätze wurden nicht ausgegeben (in den Gesprächen am 10.10.2023 vor 15 Uhr.), insgesamt ca. 6 Sätze; ausgegeben wurden ca. 10.
Tobias holt mich immer von zu hause ab mit dem Bus.
Naja eigentlich habe ich im Diktat nie einen Fehler.

Bitte <b>immer</b> einen (oder mehrere) Screenshot(s) des Fehlers einfügen.

**Zusätzliche Hinweise**

Zusätzliche Hinweise, die den Fehler besser nachvollziehbar machen.

**Comment by peterfromberger** [comment]
@AnnaViContact Hallo Anna, kannst du mir hier bitte folgende Files hochladen:

C:\Users\[dein benutzername]\AppData\Roaming\ViContact App\logs --> Bitte main.log und main.old.log (wenn vorhanden)

C:\Users\[dein benutzername]\AppData\LocalLow\UMG\vc-unity --> Player.log und Player-prev.log

Danke!

**Comment by AnnaViContact** [comment]
Ich bin leider schon aus dem Büro und morgen nicht drin. Donnerstagmorgen werde ich die Dateien schicken.
________________________________
Von: Peter Fromberger ***@***.***>
Gesendet: Dienstag, 10. Oktober 2023 16:23
An: peterfromberger/vc2-app-issues ***@***.***>
Cc: Tamm, Anett ***@***.***>; Mention ***@***.***>
Betreff: Re: [peterfromberger/vc2-app-issues] FEHLER (Issue #9)


@AnnaViContact<https://github.com/AnnaViContact> Hallo Anna, kannst du mir hier bitte folgende Files hochladen:

C:\Users[dein benutzername]\AppData\Roaming\ViContact App\logs --> Bitte main.log und main.old.log (wenn vorhanden)

C:\Program Files (x86)\ViContact\resources\chatscript_vc2\LOGS --> serverlog1024.txt

Danke!

**Comment by peterfromberger** [comment]
> Ich bin leider schon aus dem Büro und morgen nicht drin. Donnerstagmorgen werde ich die Dateien schicken.

Kein problem, ich hatte ursprünglich die falschen Pfade angegeben, hier die korrigierten:

C:\Users\dein benutzername\AppData\Roaming\ViContact App\logs --> Bitte main.log und main.old.log (wenn vorhanden)

C:\Users\dein benutzername\AppData\LocalLow\UMG\vc-unity --> Player.log und Player-prev.log (wenn vorhanden)

Hattest du die VR-Brille auf oder dir den Ton über einen Lautsprecher etc. ausgeben lassen?

**Comment by AnnaViContact** [comment]
[main.log](https://github.com/peterfromberger/vc2-app-issues/files/12879277/main.log)
[main.old.log](https://github.com/peterfromberger/vc2-app-issues/files/12879279/main.old.log)
[Player.log](https://github.com/peterfromberger/vc2-app-issues/files/12879300/Player.log)
[Player-prev.log](https://github.com/peterfromberger/vc2-app-issues/files/12879301/Player-prev.log)
Ich hatte die VR-Brille auf.

**Comment by peterfromberger** [comment]
Dankeschön. Ich konnte das Problem identifizieren. Es konnte bei bestimmten Antworten der Kinder kein Audio ausgegeben werden, da ein entsprechender Audiofile noch nicht vorliegt. Dies passiert immer dann, wenn Nils in Chatscript schon eine Antwort geändert hat, ich aber noch keinen entsprechenden neuen Audiofile vorliegen habe. Konkret heißt das beispielsweise für Constantin und dein Gespräch (9x kein Audio ausgegeben):

- er holt mich immer von zu hause ab mit dem bus ---> tobias holt mich immer von zu hause ab mit dem bus (in CS von Nils)
- Dann fahren wir noch die anderen abholen. Das dauert ganz schön lange.  ---> Dann fahren wir mit dem Bus noch die anderen abholen. Das dauert ganz schön lange. (in CS von Nils)
- Ich sitze immer vorne, aber da ist mir langweilig. ---> Im Bus sitze ich immer vorne, aber da ist mir langweilig.
- Weil ich niemanden zum Quatschen habe. (Neu in CS von Nils)
- Naja, eigentlich hab ich nie einen Fehler. ---> Naja, eigentlich hab ich beim Diktat nie einen Fehler. (in CS von Nils)
- Ich kann nie mit den anderen quatschen, die hinten sitzen. ---> Ich kann nie mit den anderen quatschen, die hinten im Bus sitzen. (CS von Nils) 
- Mein Arm hat drei Tage lang wehgetan. ---> Als Tobias mich so angefasst hat, hat mein Arm  drei Tage lang wehgetan. (in CS von Nils)
- Ich hatte auch einen blauen Fleck. ---> Ich hatte auch einen blauen Fleck am Arm. (CS von Nils)
- Ich war zu langsam beim Einsteigen. Da wird er immer sauer. ---> Ich war zu langsam beim Einsteigen. Da wird Tobias immer sauer. (in CS von Nils)

**Dies gilt auch für alle anderen Kinder. In der aktuellen Version der App können Änderungen innerhalb von Chatscript durch Nils an den Sätzen, die die Kinder antworten, noch nicht ausgegeben werden. Dies ist erst möglich, sobald die Audiofiles für die neuen Sätze/Antworten vorliegen und in die App integriert worden sind. Es ist also kein Fehler der App, sondern dem frühen Stadium der Chatscript Änderungen geschuldet.**
